// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEWsGeP7fKPb-eF3aZRmeaewT4WSgijbE',
    appId: '1:711706986241:web:c81813caa1d261a5f3fd00',
    messagingSenderId: '711706986241',
    projectId: 'ouchenemohamednourelislem',
    authDomain: 'ouchenemohamednourelislem.firebaseapp.com',
    storageBucket: 'ouchenemohamednourelislem.appspot.com',
    measurementId: 'G-4LZVPWXQVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOHYXquBdb56_Zbm3vLvo-5Og3wtuNaMc',
    appId: '1:711706986241:android:ce2d438887a97175f3fd00',
    messagingSenderId: '711706986241',
    projectId: 'ouchenemohamednourelislem',
    storageBucket: 'ouchenemohamednourelislem.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEWsGeP7fKPb-eF3aZRmeaewT4WSgijbE',
    appId: '1:711706986241:web:cc3694249c3e1e25f3fd00',
    messagingSenderId: '711706986241',
    projectId: 'ouchenemohamednourelislem',
    authDomain: 'ouchenemohamednourelislem.firebaseapp.com',
    storageBucket: 'ouchenemohamednourelislem.appspot.com',
    measurementId: 'G-7LCBVX7NYC',
  );
}
